apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /video-service
  name: video-service
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|video-service'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      serviceAccountName: video-service-account
      containers:
      - name: video-service
        image: sjw980523/video-service:ver-original
        ports:
        - containerPort: 5000
        env:
        - name: VIDEO_SERVER_IP
          value: "192.168.10.115"
        - name: VIDEO_SERVER_PORT
          value: "31000"
        - name: EDGE_SERVER_IP
          value: "192.168.10.107"
        - name: EDGE_SERVER_PORT
          value: "31001"
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: /video-service
  name: video-service
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|video-service'
spec:
  selector:
    app: video
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31000
  type: NodePort
